### PR TITLE
Add support for 7.5" waveshare screen, version 2 (800x480 display and…

### PR DESCRIPTION
**Pull request by za3k**
… support for fast update)

Compare against tag 0.1 to see changes--I couldn't get master to work. Sorry!

### CODE REVIEW

**Comment by picnoir** [comment]
I can't really test that myself: I don't own the v1 hardware anymore. I'll trust you on that one.

**Comment by za3k** [comment]
You should probably revert fc397b170b614db24af9fa662b1e1aa9c526fb44 until my PR is merged into logkeys?

**Comment by picnoir** [comment]
I don't think there's any user here besides you.

I'll revert that if an issue pops up.

**Comment by PeterMcCann07** [comment]
Hey Za3k I'm currently trying to implement this on my raspberry pi 4 and 7in5 v2 waveshare screen and I'm getting a malloc corrupted top size error. I was wondering if you know anything about this or experienced it at any point

**Comment by za3k** [comment]
I don't recall. Have you tried valgrind?

**Comment by PeterMcCann07** [comment]
I have not but I will tomorrow and see what is up, thank you

**Comment by PeterMcCann07** [comment]
Sadly I ran each file through valgrind and nothing, I think I'll move onto another typewriter project

**Pull request merged**
